/*
 *Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 *By starting with 1 and 2, the first 10 terms will be:
 *1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
*/

with Pingala(start1, start2) as 
(
    select
        1 start1,
        2 start2 
    from
        dual 
    union all
    select
        start2,
        start1 + start2 
    from
        Pingala 
    where
        start1 <= 4000000 
)
select
    sum(start1) as answer 
from
    Pingala 
where
    start1 <= 4000000 
    and mod(start1, 2) = 0;
    
